### ISSUE TITLE
"Error when verifying signature" on Linux Host with v2.0.0

### ISSUE THREAD

**Issue by kspearrin** [brucedog/U2F_Core#13]
Just upgraded to v2.0.0 and am testing it out. It works great on Windows, however, fails on Linux (maybe macOS too, have not tested that).

Trying to call `FinishRegistration` on a Linux (Debian) host causes `U2fException` (Error when verifying signature). Stack trace shows it coming from the `CheckSignature` method.

Reverting back to v1.0.4 resolves the problem.

```
U2F.Core.Exceptions.U2fException: Error when verifying signature
   at U2F.Core.Crypto.CryptoService.CheckSignature(X509Certificate2 attestationCertificate, Byte[] signedBytes, Byte[] signature)
   at U2F.Core.Models.RawRegisterResponse.CheckSignature(String appId, String clientData)
   at U2F.Core.Crypto.U2F.FinishRegistration(StartedRegistration startedRegistration, RegisterResponse tokenResponse, HashSet`1 facets)
   at Bit.Core.Services.UserService.CompleteU2fRegistrationAsync(User user, Int32 id, String name, String deviceResponse) in /home/bitwarden/Projects/bitwarden/core/src/Core/Services/Implementations/UserService.cs:line 330
   at Bit.Api.Controllers.TwoFactorController.PutU2f(TwoFactorU2fRequestModel model) in /home/bitwarden/Projects/bitwarden/core/src/Api/Controllers/TwoFactorController.cs:line 221
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()
```

My guess is some break in the new crypto libs being used.

**Comment by brucedog** [comment]
Hey Kyle

How did you generate the error? Were you using a yubico key? We’re you using the demo web app or did you pull the library into your own project?

Thanks
Bryce

**Comment by kspearrin** [comment]
I have a yubikey NEO and the blue FIDO yubikey. Both produce the problem.

I am using this in my own project here: https://github.com/bitwarden/core/blob/master/src/Core/Services/Implementations/UserService.cs#L311

**Comment by brucedog** [comment]
It looks like the issue stems from the usage of ECDsaCng and decoding the public key with the CngKey import function. I will look into the issue.

**Comment by dbeinder** [comment]
Yes, at the moment Mono implements very little of the new Cng functionality: https://github.com/mono/mono/issues/9463

Would it be possible to refactor the ICryptoService interface to return an opaque value instead of CngKey and make it public, so we can supply a custom BouncyCastle backed implementation in the meantime? Also it would be neat to split off the model classes into a separate nuget package, so we can use those without crypto dependencies in the U2F host / client facing logic.

**Comment by brucedog** [comment]
Hey David I could look into possibly returning a byte[] instead.

**Comment by brucedog** [comment]
@dbeinder Do you think I should create two nuget packages. The first being the U2F.Core package and the second being the U2F.Core.BouncyCastle?

**Comment by dbeinder** [comment]
Yes, since most users won't need the BouncyCastle version and this way they can avoid a dependency on Portable.BouncyCastle which is fairly large (3MB+)

**Comment by brucedog** [comment]
Nuget packages have been published. The U2F nuget package that supports linux/mac can be found here -> https://www.nuget.org/packages/U2F.Core.Crypto.BouncyCastle/2.0.1

**Comment by Kukks** [comment]
Hey @brucedog  I'm also experiencing this issue(`Error when verifying signature`) using `U2F.Core.Crypto.BouncyCastle/2.0.1` on a linux machine.

**Comment by dbeinder** [comment]
The Crypto.BouncyCastle implementation needs to be set manually:
`U2F.Core.Crypto.U2F.Crypto = new BouncyCastleCryptoService();`
